version: "3.9"
services:
  aihr.server:
    image: aihr.server:latest
    container_name: aihr.server
    networks:
      - aihr-network
    build:
      context: .
      dockerfile: ./src/AIHR.Server/Dockerfile
  aihr.client:
    image: aihr.client:latest
    container_name: aihr.client
    networks:
      - aihr-network
    build:
      context: .
      dockerfile: ./src/AIHR.Client/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - aihr.server
networks:
  aihr-network:
    name: aihr-internal-network
    driver: bridge